name: Python Make Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the Python Version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Linting
      - name: Lint code with flake8
        run: |
          pip install flake8 
          flake8 . --max-line-length=88

      # Run tests (when tests/ directory exists)
      # - name: Run tests with pytest
      #   run: |
      #     pip install pytest
      #     pytest tests/ --maxfail=1 --disable-warnings -q
