name: Python Make Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the Python Version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Linting
      - name: Lint code with flake8
        run: |
          pip install flake8 
          flake8 src/ --max-line-length=120 --ignore=W291,W293,F401,F541,E501,E203,F841,E226,F402,W503,E402,W292,E302,E305 --exclude=env,venv,.venv,node_modules

      # Security scan for vulnerabilities
      - name: Run security scan with bandit
        run: |
          pip install bandit
          bandit -r . --exclude ./env,./venv,./.venv --format json --output bandit-report.json || true
          bandit -r . --exclude ./env,./venv,./.venv || true

      # Dependency vulnerability scan
      - name: Run safety check
        run: |
          pip install safety
          safety check --json --output safety-report.json || true
          safety check || true

      # Run tests
      - name: Run tests
        env:
          SUPABASE_URL: "https://test.supabase.co"
          SUPABASE_KEY: "test_key"
          API_KEY: "test_api_key"
        run: |
          pip install pytest pytest-mock
          pytest src/tests/ --maxfail=3 --disable-warnings -v